services:
  kafka:
    image: bitnami/kafka:latest
    container_name: kafka
    ports:
      - "9092:9092"
    environment:
      - KAFKA_ENABLE_KRAFT=yes
      - KAFKA_CFG_NODE_ID=1
      - KAFKA_CFG_PROCESS_ROLES=controller,broker
      - KAFKA_CFG_CONTROLLER_LISTENER_NAMES=CONTROLLER
      - KAFKA_CFG_LISTENERS=PLAINTEXT://:9092,CONTROLLER://:9093
      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://kafka:9092
      - KAFKA_CFG_CONTROLLER_QUORUM_VOTERS=1@kafka:9093
      - KAFKA_KRAFT_CLUSTER_ID=d9f689b2-02e3-4820-8fc1-4efcb45762e9
      - KAFKA_CFG_AUTO_CREATE_TOPICS_ENABLE=true
      - FEATURES_KAFKA_ENABLED=true
    volumes:
      - kafka_data:/bitnami/kafka
    networks:
      - micro-net 
  
  discovery-server:
    image: daoud3d/discovery-server:v1.0.0
    container_name: discovery-server
    ports:
      - "8761:8761"
    environment:
      - SERVER_PORT=8761
      - SPRING_ACTIVE_PROFILE=default
    networks:
      - micro-net      

  order-service:
    image: daoud3d/order-service:v1.0.0
    container_name: order-service
    ports:
      - "8081:8081"
    depends_on:
      - kafka
    environment:
      - SERVER_PORT=8081
      - SPRING_KAFKA_BOOTSTRAP_SERVERS=kafka:9092
      - SPRING_KAFKA_PRODUCER_ACKS=all
      - SPRING_KAFKA_PRODUCER_RETRIES=3
      - SPRING_KAFKA_PRODUCER_LINGER_MS=5
      - SPRING_KAFKA_PRODUCER_BATCH_SIZE=16384
      - ORDER_TOPIC_NAME=order-events
      - INVENTORY_STATUS_TOPIC_NAME=inventory-status-events
      - FEATURES_KAFKA_ENABLED=true
      - LOGGING_FILE_NAME=/logs/app.log
      - SPRING_PROFILES_ACTIVE=default
    volumes:
      - ./logs/order:/logs
    networks:
      - micro-net
    
  inventory-service:
    image: daoud3d/inventory-service:v1.0.0
    container_name: inventory-service
    ports:
      - "8082:8082"
    depends_on:
      - kafka
    environment:
      - SERVER_PORT=8082
      - SPRING_KAFKA_BOOTSTRAP_SERVERS=kafka:9092
      - ORDER_TOPIC_NAME=order-events
      - INVENTORY_STATUS_TOPIC_NAME=inventory-status-events
      - FEATURES_KAFKA_ENABLED=true
      - LOGGING_FILE_NAME=/logs/app.log
      - SPRING_PROFILES_ACTIVE=default
    volumes:
      - ./logs/inventory:/logs
    networks:
      - micro-net
  
  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    depends_on:
      - order-service
      - inventory-service
    networks:
      - micro-net

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    ports:
      - "3000:3000"
    volumes:
      - grafana-storage:/var/lib/grafana
    depends_on:
      - prometheus
    networks:
      - micro-net

  opensearch:
    image: opensearchproject/opensearch:2.11.1
    container_name: opensearch
    environment:
      - discovery.type=single-node
      - plugins.security.disabled=true
      - bootstrap.memory_lock=true
      - OPENSEARCH_JAVA_OPTS=-Xms512m -Xmx512m
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - os-data:/usr/share/opensearch/data
    ports:
      - "9200:9200"   # REST API
      - "9600:9600"   # Performance analyzer
    networks:
      - micro-net

  opensearch-dashboards:
    image: opensearchproject/opensearch-dashboards:2.11.1
    container_name: opensearch-dashboards
    depends_on:
      - opensearch
    ports:
      - "5601:5601"   # Web UI
    environment:
      - OPENSEARCH_HOSTS=http://opensearch:9200
      - DISABLE_SECURITY_DASHBOARDS_PLUGIN=true
    networks:
      - micro-net
    
  fluent-bit:
    image: cr.fluentbit.io/fluent/fluent-bit:2.2.2
    container_name: fluent-bit
    depends_on:
      - opensearch
    volumes:
      - ./fluent-bit.conf:/fluent-bit/etc/fluent-bit.conf:ro
      - ./parsers.conf:/fluent-bit/etc/parsers.conf:ro
      - ./logs:/logs:ro
      - ./fluentbit:/fluentbit
    networks:
      - micro-net

volumes:
  kafka_data:
  grafana-storage:
  os-data:  
    
networks:
  micro-net:
    driver: bridge    
