spring:
  application:
    name: inventory-service
  


kafka:
  bootstrap-servers: ${SPRING_KAFKA_BOOTSTRAP_SERVERS:kafka:9092}
  order-topic: ${ORDER_TOPIC_NAME:order-events}
  group-id: inventory-consumer-group  

server:
  port: ${SERVER_PORT:8082} 
    
